//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityEngineORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int Test_code { get; set; }
        public string Test_title { get; set; }
        public System.Guid Test_GUID { get; set; }
        public bool Theory_flag { get; set; }
        public string Theory_Source { get; set; }
        public System.TimeSpan Test_time { get; set; }
        public int Questions_amount { get; set; }
        public int Amount_for_pass { get; set; }
        public Nullable<int> Image_code { get; set; }
        public Nullable<int> Theory_code { get; set; }
    
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Theory Theory { get; set; }
    }
}
